version: "3.9"

services:
  gateway-go:
    build: ./gateway-go
    ports:
      - "8080:8080"

  user-service-go:
    build: ./user-service-go
    ports:
      - "50051:50051"

  order-service-go:
    build: ./order-service-go
    ports:
      - "50052:50052"

  catalog-service-py:
    build: ./catalog-service-py
    ports:
      - "50053:50053"
      - "8001:8001"
