apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-go
  namespace: bookstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-go
  template:
    metadata:
      labels:
        app: gateway-go
    spec:
      containers:
        - name: gateway-go
          image: gateway-go:latest
          ports:
            - containerPort: 8080
