apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-go
  namespace: bookstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service-go
  template:
    metadata:
      labels:
        app: order-service-go
    spec:
      containers:
        - name: order-service-go
          image: order-service-go:latest
          ports:
            - containerPort: 50052
