apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service-py
  namespace: bookstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service-py
  template:
    metadata:
      labels:
        app: payment-service-py
    spec:
      containers:
        - name: payment-service-py
          image: payment-service-py:latest
          ports:
            - containerPort: 50054
            - containerPort: 8002
